spring.application.name=auth-service

server.port=8089

# ==============================
# DATABASE
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/atcmaafa
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / HIBERNATE
# ==============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# JWT
# ==============================
jwt.secret=D55zJMSZcQcqj4Vyrniaxc+Sp2lv+1330o36xY72/mY=
jwt.expiration=900000